package CommunicationSystemApp;


/**
* CommunicationSystemApp/_CommunicationImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/

public abstract class _CommunicationImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements CommunicationSystemApp.Communication, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CommunicationImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("newUser", new java.lang.Integer (0));
    _methods.put ("getUser", new java.lang.Integer (1));
    _methods.put ("joinRoom", new java.lang.Integer (2));
    _methods.put ("chatRoom", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CommunicationSystemApp/Communication/newUser
       {
         CommunicationSystemApp.AddressBook newDetails = CommunicationSystemApp.AddressBookHelper.read (in);
         this.newUser (newDetails);
         out = $rh.createReply();
         break;
       }

       case 1:  // CommunicationSystemApp/Communication/getUser
       {
         String name = in.read_string ();
         org.omg.CORBA.AnyHolder newDetails = new org.omg.CORBA.AnyHolder ();
         this.getUser (name, newDetails);
         out = $rh.createReply();
         out.write_any (newDetails.value);
         break;
       }

       case 2:  // CommunicationSystemApp/Communication/joinRoom
       {
         CommunicationSystemApp.Member member = CommunicationSystemApp.MemberHelper.read (in);
         String name = in.read_string ();
         this.joinRoom (member, name);
         out = $rh.createReply();
         break;
       }

       case 3:  // CommunicationSystemApp/Communication/chatRoom
       {
         String chat = in.read_string ();
         String name = in.read_string ();
         this.chatRoom (chat, name);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CommunicationSystemApp/Communication:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CommunicationImplBase
