package CommunicationSystemApp;


/**
* CommunicationSystemApp/_NumberGuessImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/

public abstract class _NumberGuessImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements CommunicationSystemApp.NumberGuess, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _NumberGuessImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNumber", new java.lang.Integer (0));
    _methods.put ("guess", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CommunicationSystemApp/NumberGuess/getNumber
       {
         int $result = (int)0;
         $result = this.getNumber ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // CommunicationSystemApp/NumberGuess/guess
       {
         double amount = in.read_double ();
         double $result = (double)0;
         $result = this.guess (amount);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CommunicationSystemApp/NumberGuess:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _NumberGuessImplBase
