package CommunicationSystemApp;


/**
* CommunicationSystemApp/Communication_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/

public class Communication_Tie extends _CommunicationImplBase
{

  // Constructors
  public Communication_Tie ()
  {
  }

  public Communication_Tie (CommunicationSystemApp.CommunicationOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void newUser (CommunicationSystemApp.AddressBook newDetails)
  {
    _impl.newUser(newDetails);
  } // newUser

  public void getUser (String name, org.omg.CORBA.AnyHolder newDetails)
  {
    _impl.getUser(name, newDetails);
  } // getUser

  public void joinRoom (CommunicationSystemApp.Member member, String name)
  {
    _impl.joinRoom(member, name);
  } // joinRoom

  public void chatRoom (String chat, String name)
  {
    _impl.chatRoom(chat, name);
  } // chatRoom

  private CommunicationSystemApp.CommunicationOperations _impl;

} // class Communication_Tie
