package CommunicationSystemApp;


/**
* CommunicationSystemApp/CommunicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/

public interface CommunicationOperations 
{
  void newUser (CommunicationSystemApp.AddressBook newDetails);
  void getUser (String name, org.omg.CORBA.AnyHolder newDetails);
  void joinRoom (CommunicationSystemApp.Member member, String name);
  void chatRoom (String chat, String name);
} // interface CommunicationOperations
