package CommunicationSystemApp;


/**
* CommunicationSystemApp/MemberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/


// Declare the interfaces
public interface MemberOperations 
{
  void callBack (String message);
} // interface MemberOperations
