package CommunicationSystemApp;


/**
* CommunicationSystemApp/Member_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/


// Declare the interfaces
public class Member_Tie extends _MemberImplBase
{

  // Constructors
  public Member_Tie ()
  {
  }

  public Member_Tie (CommunicationSystemApp.MemberOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBack (String message)
  {
    _impl.callBack(message);
  } // callBack

  private CommunicationSystemApp.MemberOperations _impl;

} // class Member_Tie
