package CommunicationSystemApp;


/**
* CommunicationSystemApp/NumberGuess_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Conal/Documents/Distributed Systems Project/Communication/CommunicationSystem.idl
* Saturday, 12 April 2014 21:10:40 o'clock BST
*/

public class NumberGuess_Tie extends _NumberGuessImplBase
{

  // Constructors
  public NumberGuess_Tie ()
  {
  }

  public NumberGuess_Tie (CommunicationSystemApp.NumberGuessOperations impl)
  {
    super ();
    _impl = impl;
  }

  public int getNumber ()
  {
    return _impl.getNumber();
  } // getNumber

  public double guess (double amount)
  {
    return _impl.guess(amount);
  } // guess

  private CommunicationSystemApp.NumberGuessOperations _impl;

} // class NumberGuess_Tie
